
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mzj10
 */
public class length extends javax.swing.JFrame {
    
    
    
    
    static HomePage previous;
    public length(HomePage p) {
        initComponents();
        setSize(450,400);
        setTitle("Length Calculator");
        setLocationRelativeTo(null);
        setVisible(true);
        previous = p;
        jButton21.setContentAreaFilled(false); //to make the content area transparent
        jButton21.setBorderPainted(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 120, 180, 30);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel3.setText("Courrency Converter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 30, 290, 50);

        jPanel1.setBackground(new java.awt.Color(102, 198, 60));
        jPanel1.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "SAR", "MYR" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(200, 170, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("From:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 170, 60, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "SAR", "MYR" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(200, 220, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("To:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 220, 60, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(80, 260, 240, 90);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Enter a value:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 110, 40);

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton21.setText(">");
        jButton21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton21.setBorderPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);
        jButton21.setBounds(370, 20, 50, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 290, 100, 30);

        jCheckBox1.setText("No decimal");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(330, 260, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.setVisible(false);
        previous.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        if (jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter a value");
        }
        else {
        double value = Double.parseDouble(jTextField1.getText());
       String from = this.jComboBox1.getSelectedItem().toString();
       String to = this.jComboBox2.getSelectedItem().toString();
       double converted = 0.0;
       String result = "";
       int check = 0;
       if (jCheckBox1.isSelected()){
           check = 1;
       }
       switch(from){
        
           case "USD":
               switch(to){
                   
                   case "USD":
               converted = value;
               result = "$";
                   break;
                   case "EUR":
                       
               converted = value *0.88;
               result = "€";
                   break;
                   case "SAR":
               converted = value *3.75;
               result = "SR";
                   break;
                   case "MYR":
               converted = value *4.06;
               result = "RM";
                   break;
               }
               if (check == 1){
                jTextField2.setText(result+(int)converted );   
               }else{
               jTextField2.setText(result+converted );
               }
               break;
           case "EUR":
               switch(to){
                   
                   case "USD":
               converted = value * 1.13;
                result = "$";
               
                   break;
                   case "EUR":
                       
               converted = value ;
               result = "€";
                   break;
                   case "SAR":
               converted = value *4.25;
               result = "SR";
                   break;
                   case "MYR":
               converted = value *4.61;
               result = "RM";
                   break;
               }
              if (check == 1){
                jTextField2.setText(result+(int)converted );   
               }else{
               jTextField2.setText(result+converted );
               }
               break;
           case "SAR":
               switch(to){
                   
                   case "USD":
               converted = value * 0.26;
                result = "$";
                   break;
                   case "EUR":
                       
               converted = value *0.23;
               result = "€";
                   break;
                   case "SAR":
               converted = value ;
               result = "SR";
                   break;
                   case "MYR":
               converted = value *1.08;
               result = "RM";
                   break;
               }
              if (check == 1){
                jTextField2.setText(result+(int)converted );   
               }else{
               jTextField2.setText(result+converted );
               }
               break;
           case "MYR":
               switch(to){
                   
                   case "USD":
               converted = value* 0.24;
                result = "$";
                   break;
                   case "EUR":
                       
               converted = value *0.21;
               result = "€";
                   break;
                   case "SAR":
               converted = value *0.92;
               result = "SR";
                   break;
                   case "MYR":
               converted = value ;
               result = "RM";
                   break;
               }
               if (check == 1){
                jTextField2.setText(result+(int)converted );   
               }else{
               jTextField2.setText(result+converted );
               }
               break;
               
        
        
        
        
        
        
    }
       
       
       
        }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new length(previous).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton21;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
